// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test.proto

package com.hujing.netty.protobuf;

public final class DateInfo {
  private DateInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OneOfAllOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hujing.protobuf.OneOfAll)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.hujing.protobuf.OneOfAll.DataType date_type = 1;</code>
     */
    boolean hasDateType();
    /**
     * <code>required .com.hujing.protobuf.OneOfAll.DataType date_type = 1;</code>
     */
    com.hujing.netty.protobuf.DateInfo.OneOfAll.DataType getDateType();

    /**
     * <code>optional .com.hujing.protobuf.Employee employee = 2;</code>
     */
    boolean hasEmployee();
    /**
     * <code>optional .com.hujing.protobuf.Employee employee = 2;</code>
     */
    com.hujing.netty.protobuf.DateInfo.Employee getEmployee();
    /**
     * <code>optional .com.hujing.protobuf.Employee employee = 2;</code>
     */
    com.hujing.netty.protobuf.DateInfo.EmployeeOrBuilder getEmployeeOrBuilder();

    /**
     * <code>optional .com.hujing.protobuf.Person person = 3;</code>
     */
    boolean hasPerson();
    /**
     * <code>optional .com.hujing.protobuf.Person person = 3;</code>
     */
    com.hujing.netty.protobuf.DateInfo.Person getPerson();
    /**
     * <code>optional .com.hujing.protobuf.Person person = 3;</code>
     */
    com.hujing.netty.protobuf.DateInfo.PersonOrBuilder getPersonOrBuilder();

    public com.hujing.netty.protobuf.DateInfo.OneOfAll.DataBodyCase getDataBodyCase();
  }
  /**
   * Protobuf type {@code com.hujing.protobuf.OneOfAll}
   */
  public  static final class OneOfAll extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.hujing.protobuf.OneOfAll)
      OneOfAllOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OneOfAll.newBuilder() to construct.
    private OneOfAll(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OneOfAll() {
      dateType_ = 1;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OneOfAll();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OneOfAll(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.hujing.netty.protobuf.DateInfo.OneOfAll.DataType value = com.hujing.netty.protobuf.DateInfo.OneOfAll.DataType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                dateType_ = rawValue;
              }
              break;
            }
            case 18: {
              com.hujing.netty.protobuf.DateInfo.Employee.Builder subBuilder = null;
              if (dataBodyCase_ == 2) {
                subBuilder = ((com.hujing.netty.protobuf.DateInfo.Employee) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(com.hujing.netty.protobuf.DateInfo.Employee.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.hujing.netty.protobuf.DateInfo.Employee) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 2;
              break;
            }
            case 26: {
              com.hujing.netty.protobuf.DateInfo.Person.Builder subBuilder = null;
              if (dataBodyCase_ == 3) {
                subBuilder = ((com.hujing.netty.protobuf.DateInfo.Person) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(com.hujing.netty.protobuf.DateInfo.Person.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.hujing.netty.protobuf.DateInfo.Person) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hujing.netty.protobuf.DateInfo.internal_static_com_hujing_protobuf_OneOfAll_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hujing.netty.protobuf.DateInfo.internal_static_com_hujing_protobuf_OneOfAll_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hujing.netty.protobuf.DateInfo.OneOfAll.class, com.hujing.netty.protobuf.DateInfo.OneOfAll.Builder.class);
    }

    /**
     * Protobuf enum {@code com.hujing.protobuf.OneOfAll.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>EMP = 1;</code>
       */
      EMP(1),
      /**
       * <code>PERSON = 2;</code>
       */
      PERSON(2),
      ;

      /**
       * <code>EMP = 1;</code>
       */
      public static final int EMP_VALUE = 1;
      /**
       * <code>PERSON = 2;</code>
       */
      public static final int PERSON_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      public static DataType forNumber(int value) {
        switch (value) {
          case 1: return EMP;
          case 2: return PERSON;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.hujing.netty.protobuf.DateInfo.OneOfAll.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.hujing.protobuf.OneOfAll.DataType)
    }

    private int bitField0_;
    private int dataBodyCase_ = 0;
    private java.lang.Object dataBody_;
    public enum DataBodyCase
        implements com.google.protobuf.Internal.EnumLite {
      EMPLOYEE(2),
      PERSON(3),
      DATABODY_NOT_SET(0);
      private final int value;
      private DataBodyCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataBodyCase forNumber(int value) {
        switch (value) {
          case 2: return EMPLOYEE;
          case 3: return PERSON;
          case 0: return DATABODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataBodyCase
    getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public static final int DATE_TYPE_FIELD_NUMBER = 1;
    private int dateType_;
    /**
     * <code>required .com.hujing.protobuf.OneOfAll.DataType date_type = 1;</code>
     */
    public boolean hasDateType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .com.hujing.protobuf.OneOfAll.DataType date_type = 1;</code>
     */
    public com.hujing.netty.protobuf.DateInfo.OneOfAll.DataType getDateType() {
      @SuppressWarnings("deprecation")
      com.hujing.netty.protobuf.DateInfo.OneOfAll.DataType result = com.hujing.netty.protobuf.DateInfo.OneOfAll.DataType.valueOf(dateType_);
      return result == null ? com.hujing.netty.protobuf.DateInfo.OneOfAll.DataType.EMP : result;
    }

    public static final int EMPLOYEE_FIELD_NUMBER = 2;
    /**
     * <code>optional .com.hujing.protobuf.Employee employee = 2;</code>
     */
    public boolean hasEmployee() {
      return dataBodyCase_ == 2;
    }
    /**
     * <code>optional .com.hujing.protobuf.Employee employee = 2;</code>
     */
    public com.hujing.netty.protobuf.DateInfo.Employee getEmployee() {
      if (dataBodyCase_ == 2) {
         return (com.hujing.netty.protobuf.DateInfo.Employee) dataBody_;
      }
      return com.hujing.netty.protobuf.DateInfo.Employee.getDefaultInstance();
    }
    /**
     * <code>optional .com.hujing.protobuf.Employee employee = 2;</code>
     */
    public com.hujing.netty.protobuf.DateInfo.EmployeeOrBuilder getEmployeeOrBuilder() {
      if (dataBodyCase_ == 2) {
         return (com.hujing.netty.protobuf.DateInfo.Employee) dataBody_;
      }
      return com.hujing.netty.protobuf.DateInfo.Employee.getDefaultInstance();
    }

    public static final int PERSON_FIELD_NUMBER = 3;
    /**
     * <code>optional .com.hujing.protobuf.Person person = 3;</code>
     */
    public boolean hasPerson() {
      return dataBodyCase_ == 3;
    }
    /**
     * <code>optional .com.hujing.protobuf.Person person = 3;</code>
     */
    public com.hujing.netty.protobuf.DateInfo.Person getPerson() {
      if (dataBodyCase_ == 3) {
         return (com.hujing.netty.protobuf.DateInfo.Person) dataBody_;
      }
      return com.hujing.netty.protobuf.DateInfo.Person.getDefaultInstance();
    }
    /**
     * <code>optional .com.hujing.protobuf.Person person = 3;</code>
     */
    public com.hujing.netty.protobuf.DateInfo.PersonOrBuilder getPersonOrBuilder() {
      if (dataBodyCase_ == 3) {
         return (com.hujing.netty.protobuf.DateInfo.Person) dataBody_;
      }
      return com.hujing.netty.protobuf.DateInfo.Person.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDateType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, dateType_);
      }
      if (dataBodyCase_ == 2) {
        output.writeMessage(2, (com.hujing.netty.protobuf.DateInfo.Employee) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        output.writeMessage(3, (com.hujing.netty.protobuf.DateInfo.Person) dataBody_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dateType_);
      }
      if (dataBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.hujing.netty.protobuf.DateInfo.Employee) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.hujing.netty.protobuf.DateInfo.Person) dataBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hujing.netty.protobuf.DateInfo.OneOfAll)) {
        return super.equals(obj);
      }
      com.hujing.netty.protobuf.DateInfo.OneOfAll other = (com.hujing.netty.protobuf.DateInfo.OneOfAll) obj;

      if (hasDateType() != other.hasDateType()) return false;
      if (hasDateType()) {
        if (dateType_ != other.dateType_) return false;
      }
      if (!getDataBodyCase().equals(other.getDataBodyCase())) return false;
      switch (dataBodyCase_) {
        case 2:
          if (!getEmployee()
              .equals(other.getEmployee())) return false;
          break;
        case 3:
          if (!getPerson()
              .equals(other.getPerson())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDateType()) {
        hash = (37 * hash) + DATE_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + dateType_;
      }
      switch (dataBodyCase_) {
        case 2:
          hash = (37 * hash) + EMPLOYEE_FIELD_NUMBER;
          hash = (53 * hash) + getEmployee().hashCode();
          break;
        case 3:
          hash = (37 * hash) + PERSON_FIELD_NUMBER;
          hash = (53 * hash) + getPerson().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hujing.netty.protobuf.DateInfo.OneOfAll parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hujing.netty.protobuf.DateInfo.OneOfAll parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hujing.netty.protobuf.DateInfo.OneOfAll parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hujing.netty.protobuf.DateInfo.OneOfAll parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hujing.netty.protobuf.DateInfo.OneOfAll parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hujing.netty.protobuf.DateInfo.OneOfAll parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hujing.netty.protobuf.DateInfo.OneOfAll parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hujing.netty.protobuf.DateInfo.OneOfAll parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hujing.netty.protobuf.DateInfo.OneOfAll parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hujing.netty.protobuf.DateInfo.OneOfAll parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hujing.netty.protobuf.DateInfo.OneOfAll parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hujing.netty.protobuf.DateInfo.OneOfAll parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hujing.netty.protobuf.DateInfo.OneOfAll prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hujing.protobuf.OneOfAll}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hujing.protobuf.OneOfAll)
        com.hujing.netty.protobuf.DateInfo.OneOfAllOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hujing.netty.protobuf.DateInfo.internal_static_com_hujing_protobuf_OneOfAll_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hujing.netty.protobuf.DateInfo.internal_static_com_hujing_protobuf_OneOfAll_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hujing.netty.protobuf.DateInfo.OneOfAll.class, com.hujing.netty.protobuf.DateInfo.OneOfAll.Builder.class);
      }

      // Construct using com.hujing.netty.protobuf.DateInfo.OneOfAll.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dateType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        dataBodyCase_ = 0;
        dataBody_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hujing.netty.protobuf.DateInfo.internal_static_com_hujing_protobuf_OneOfAll_descriptor;
      }

      @java.lang.Override
      public com.hujing.netty.protobuf.DateInfo.OneOfAll getDefaultInstanceForType() {
        return com.hujing.netty.protobuf.DateInfo.OneOfAll.getDefaultInstance();
      }

      @java.lang.Override
      public com.hujing.netty.protobuf.DateInfo.OneOfAll build() {
        com.hujing.netty.protobuf.DateInfo.OneOfAll result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hujing.netty.protobuf.DateInfo.OneOfAll buildPartial() {
        com.hujing.netty.protobuf.DateInfo.OneOfAll result = new com.hujing.netty.protobuf.DateInfo.OneOfAll(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dateType_ = dateType_;
        if (dataBodyCase_ == 2) {
          if (employeeBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = employeeBuilder_.build();
          }
        }
        if (dataBodyCase_ == 3) {
          if (personBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = personBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.dataBodyCase_ = dataBodyCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hujing.netty.protobuf.DateInfo.OneOfAll) {
          return mergeFrom((com.hujing.netty.protobuf.DateInfo.OneOfAll)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hujing.netty.protobuf.DateInfo.OneOfAll other) {
        if (other == com.hujing.netty.protobuf.DateInfo.OneOfAll.getDefaultInstance()) return this;
        if (other.hasDateType()) {
          setDateType(other.getDateType());
        }
        switch (other.getDataBodyCase()) {
          case EMPLOYEE: {
            mergeEmployee(other.getEmployee());
            break;
          }
          case PERSON: {
            mergePerson(other.getPerson());
            break;
          }
          case DATABODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasDateType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hujing.netty.protobuf.DateInfo.OneOfAll parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hujing.netty.protobuf.DateInfo.OneOfAll) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataBodyCase_ = 0;
      private java.lang.Object dataBody_;
      public DataBodyCase
          getDataBodyCase() {
        return DataBodyCase.forNumber(
            dataBodyCase_);
      }

      public Builder clearDataBody() {
        dataBodyCase_ = 0;
        dataBody_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int dateType_ = 1;
      /**
       * <code>required .com.hujing.protobuf.OneOfAll.DataType date_type = 1;</code>
       */
      public boolean hasDateType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .com.hujing.protobuf.OneOfAll.DataType date_type = 1;</code>
       */
      public com.hujing.netty.protobuf.DateInfo.OneOfAll.DataType getDateType() {
        @SuppressWarnings("deprecation")
        com.hujing.netty.protobuf.DateInfo.OneOfAll.DataType result = com.hujing.netty.protobuf.DateInfo.OneOfAll.DataType.valueOf(dateType_);
        return result == null ? com.hujing.netty.protobuf.DateInfo.OneOfAll.DataType.EMP : result;
      }
      /**
       * <code>required .com.hujing.protobuf.OneOfAll.DataType date_type = 1;</code>
       */
      public Builder setDateType(com.hujing.netty.protobuf.DateInfo.OneOfAll.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        dateType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .com.hujing.protobuf.OneOfAll.DataType date_type = 1;</code>
       */
      public Builder clearDateType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dateType_ = 1;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.hujing.netty.protobuf.DateInfo.Employee, com.hujing.netty.protobuf.DateInfo.Employee.Builder, com.hujing.netty.protobuf.DateInfo.EmployeeOrBuilder> employeeBuilder_;
      /**
       * <code>optional .com.hujing.protobuf.Employee employee = 2;</code>
       */
      public boolean hasEmployee() {
        return dataBodyCase_ == 2;
      }
      /**
       * <code>optional .com.hujing.protobuf.Employee employee = 2;</code>
       */
      public com.hujing.netty.protobuf.DateInfo.Employee getEmployee() {
        if (employeeBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            return (com.hujing.netty.protobuf.DateInfo.Employee) dataBody_;
          }
          return com.hujing.netty.protobuf.DateInfo.Employee.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 2) {
            return employeeBuilder_.getMessage();
          }
          return com.hujing.netty.protobuf.DateInfo.Employee.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.hujing.protobuf.Employee employee = 2;</code>
       */
      public Builder setEmployee(com.hujing.netty.protobuf.DateInfo.Employee value) {
        if (employeeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          employeeBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.hujing.protobuf.Employee employee = 2;</code>
       */
      public Builder setEmployee(
          com.hujing.netty.protobuf.DateInfo.Employee.Builder builderForValue) {
        if (employeeBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          employeeBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.hujing.protobuf.Employee employee = 2;</code>
       */
      public Builder mergeEmployee(com.hujing.netty.protobuf.DateInfo.Employee value) {
        if (employeeBuilder_ == null) {
          if (dataBodyCase_ == 2 &&
              dataBody_ != com.hujing.netty.protobuf.DateInfo.Employee.getDefaultInstance()) {
            dataBody_ = com.hujing.netty.protobuf.DateInfo.Employee.newBuilder((com.hujing.netty.protobuf.DateInfo.Employee) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 2) {
            employeeBuilder_.mergeFrom(value);
          }
          employeeBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.hujing.protobuf.Employee employee = 2;</code>
       */
      public Builder clearEmployee() {
        if (employeeBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          employeeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.hujing.protobuf.Employee employee = 2;</code>
       */
      public com.hujing.netty.protobuf.DateInfo.Employee.Builder getEmployeeBuilder() {
        return getEmployeeFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.hujing.protobuf.Employee employee = 2;</code>
       */
      public com.hujing.netty.protobuf.DateInfo.EmployeeOrBuilder getEmployeeOrBuilder() {
        if ((dataBodyCase_ == 2) && (employeeBuilder_ != null)) {
          return employeeBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 2) {
            return (com.hujing.netty.protobuf.DateInfo.Employee) dataBody_;
          }
          return com.hujing.netty.protobuf.DateInfo.Employee.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.hujing.protobuf.Employee employee = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.hujing.netty.protobuf.DateInfo.Employee, com.hujing.netty.protobuf.DateInfo.Employee.Builder, com.hujing.netty.protobuf.DateInfo.EmployeeOrBuilder>
          getEmployeeFieldBuilder() {
        if (employeeBuilder_ == null) {
          if (!(dataBodyCase_ == 2)) {
            dataBody_ = com.hujing.netty.protobuf.DateInfo.Employee.getDefaultInstance();
          }
          employeeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.hujing.netty.protobuf.DateInfo.Employee, com.hujing.netty.protobuf.DateInfo.Employee.Builder, com.hujing.netty.protobuf.DateInfo.EmployeeOrBuilder>(
                  (com.hujing.netty.protobuf.DateInfo.Employee) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 2;
        onChanged();;
        return employeeBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.hujing.netty.protobuf.DateInfo.Person, com.hujing.netty.protobuf.DateInfo.Person.Builder, com.hujing.netty.protobuf.DateInfo.PersonOrBuilder> personBuilder_;
      /**
       * <code>optional .com.hujing.protobuf.Person person = 3;</code>
       */
      public boolean hasPerson() {
        return dataBodyCase_ == 3;
      }
      /**
       * <code>optional .com.hujing.protobuf.Person person = 3;</code>
       */
      public com.hujing.netty.protobuf.DateInfo.Person getPerson() {
        if (personBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            return (com.hujing.netty.protobuf.DateInfo.Person) dataBody_;
          }
          return com.hujing.netty.protobuf.DateInfo.Person.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 3) {
            return personBuilder_.getMessage();
          }
          return com.hujing.netty.protobuf.DateInfo.Person.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.hujing.protobuf.Person person = 3;</code>
       */
      public Builder setPerson(com.hujing.netty.protobuf.DateInfo.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          personBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>optional .com.hujing.protobuf.Person person = 3;</code>
       */
      public Builder setPerson(
          com.hujing.netty.protobuf.DateInfo.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          personBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>optional .com.hujing.protobuf.Person person = 3;</code>
       */
      public Builder mergePerson(com.hujing.netty.protobuf.DateInfo.Person value) {
        if (personBuilder_ == null) {
          if (dataBodyCase_ == 3 &&
              dataBody_ != com.hujing.netty.protobuf.DateInfo.Person.getDefaultInstance()) {
            dataBody_ = com.hujing.netty.protobuf.DateInfo.Person.newBuilder((com.hujing.netty.protobuf.DateInfo.Person) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 3) {
            personBuilder_.mergeFrom(value);
          }
          personBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>optional .com.hujing.protobuf.Person person = 3;</code>
       */
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          personBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.hujing.protobuf.Person person = 3;</code>
       */
      public com.hujing.netty.protobuf.DateInfo.Person.Builder getPersonBuilder() {
        return getPersonFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.hujing.protobuf.Person person = 3;</code>
       */
      public com.hujing.netty.protobuf.DateInfo.PersonOrBuilder getPersonOrBuilder() {
        if ((dataBodyCase_ == 3) && (personBuilder_ != null)) {
          return personBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 3) {
            return (com.hujing.netty.protobuf.DateInfo.Person) dataBody_;
          }
          return com.hujing.netty.protobuf.DateInfo.Person.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.hujing.protobuf.Person person = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.hujing.netty.protobuf.DateInfo.Person, com.hujing.netty.protobuf.DateInfo.Person.Builder, com.hujing.netty.protobuf.DateInfo.PersonOrBuilder>
          getPersonFieldBuilder() {
        if (personBuilder_ == null) {
          if (!(dataBodyCase_ == 3)) {
            dataBody_ = com.hujing.netty.protobuf.DateInfo.Person.getDefaultInstance();
          }
          personBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.hujing.netty.protobuf.DateInfo.Person, com.hujing.netty.protobuf.DateInfo.Person.Builder, com.hujing.netty.protobuf.DateInfo.PersonOrBuilder>(
                  (com.hujing.netty.protobuf.DateInfo.Person) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 3;
        onChanged();;
        return personBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.hujing.protobuf.OneOfAll)
    }

    // @@protoc_insertion_point(class_scope:com.hujing.protobuf.OneOfAll)
    private static final com.hujing.netty.protobuf.DateInfo.OneOfAll DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hujing.netty.protobuf.DateInfo.OneOfAll();
    }

    public static com.hujing.netty.protobuf.DateInfo.OneOfAll getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<OneOfAll>
        PARSER = new com.google.protobuf.AbstractParser<OneOfAll>() {
      @java.lang.Override
      public OneOfAll parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OneOfAll(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OneOfAll> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OneOfAll> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hujing.netty.protobuf.DateInfo.OneOfAll getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmployeeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hujing.protobuf.Employee)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string username = 1;</code>
     */
    boolean hasUsername();
    /**
     * <code>optional string username = 1;</code>
     */
    java.lang.String getUsername();
    /**
     * <code>optional string username = 1;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>optional int32 age = 2;</code>
     */
    boolean hasAge();
    /**
     * <code>optional int32 age = 2;</code>
     */
    int getAge();

    /**
     * <code>optional string address = 3;</code>
     */
    boolean hasAddress();
    /**
     * <code>optional string address = 3;</code>
     */
    java.lang.String getAddress();
    /**
     * <code>optional string address = 3;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();
  }
  /**
   * Protobuf type {@code com.hujing.protobuf.Employee}
   */
  public  static final class Employee extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.hujing.protobuf.Employee)
      EmployeeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Employee.newBuilder() to construct.
    private Employee(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Employee() {
      username_ = "";
      address_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Employee();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Employee(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              username_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              age_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              address_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hujing.netty.protobuf.DateInfo.internal_static_com_hujing_protobuf_Employee_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hujing.netty.protobuf.DateInfo.internal_static_com_hujing_protobuf_Employee_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hujing.netty.protobuf.DateInfo.Employee.class, com.hujing.netty.protobuf.DateInfo.Employee.Builder.class);
    }

    private int bitField0_;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object username_;
    /**
     * <code>optional string username = 1;</code>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string username = 1;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string username = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>optional int32 age = 2;</code>
     */
    public boolean hasAge() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 3;
    private volatile java.lang.Object address_;
    /**
     * <code>optional string address = 3;</code>
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string address = 3;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string address = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, username_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, age_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, address_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, username_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, address_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hujing.netty.protobuf.DateInfo.Employee)) {
        return super.equals(obj);
      }
      com.hujing.netty.protobuf.DateInfo.Employee other = (com.hujing.netty.protobuf.DateInfo.Employee) obj;

      if (hasUsername() != other.hasUsername()) return false;
      if (hasUsername()) {
        if (!getUsername()
            .equals(other.getUsername())) return false;
      }
      if (hasAge() != other.hasAge()) return false;
      if (hasAge()) {
        if (getAge()
            != other.getAge()) return false;
      }
      if (hasAddress() != other.hasAddress()) return false;
      if (hasAddress()) {
        if (!getAddress()
            .equals(other.getAddress())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUsername()) {
        hash = (37 * hash) + USERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getUsername().hashCode();
      }
      if (hasAge()) {
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + getAge();
      }
      if (hasAddress()) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddress().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hujing.netty.protobuf.DateInfo.Employee parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hujing.netty.protobuf.DateInfo.Employee parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hujing.netty.protobuf.DateInfo.Employee parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hujing.netty.protobuf.DateInfo.Employee parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hujing.netty.protobuf.DateInfo.Employee parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hujing.netty.protobuf.DateInfo.Employee parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hujing.netty.protobuf.DateInfo.Employee parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hujing.netty.protobuf.DateInfo.Employee parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hujing.netty.protobuf.DateInfo.Employee parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hujing.netty.protobuf.DateInfo.Employee parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hujing.netty.protobuf.DateInfo.Employee parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hujing.netty.protobuf.DateInfo.Employee parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hujing.netty.protobuf.DateInfo.Employee prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hujing.protobuf.Employee}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hujing.protobuf.Employee)
        com.hujing.netty.protobuf.DateInfo.EmployeeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hujing.netty.protobuf.DateInfo.internal_static_com_hujing_protobuf_Employee_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hujing.netty.protobuf.DateInfo.internal_static_com_hujing_protobuf_Employee_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hujing.netty.protobuf.DateInfo.Employee.class, com.hujing.netty.protobuf.DateInfo.Employee.Builder.class);
      }

      // Construct using com.hujing.netty.protobuf.DateInfo.Employee.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hujing.netty.protobuf.DateInfo.internal_static_com_hujing_protobuf_Employee_descriptor;
      }

      @java.lang.Override
      public com.hujing.netty.protobuf.DateInfo.Employee getDefaultInstanceForType() {
        return com.hujing.netty.protobuf.DateInfo.Employee.getDefaultInstance();
      }

      @java.lang.Override
      public com.hujing.netty.protobuf.DateInfo.Employee build() {
        com.hujing.netty.protobuf.DateInfo.Employee result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hujing.netty.protobuf.DateInfo.Employee buildPartial() {
        com.hujing.netty.protobuf.DateInfo.Employee result = new com.hujing.netty.protobuf.DateInfo.Employee(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.age_ = age_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.address_ = address_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hujing.netty.protobuf.DateInfo.Employee) {
          return mergeFrom((com.hujing.netty.protobuf.DateInfo.Employee)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hujing.netty.protobuf.DateInfo.Employee other) {
        if (other == com.hujing.netty.protobuf.DateInfo.Employee.getDefaultInstance()) return this;
        if (other.hasUsername()) {
          bitField0_ |= 0x00000001;
          username_ = other.username_;
          onChanged();
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        if (other.hasAddress()) {
          bitField0_ |= 0x00000004;
          address_ = other.address_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hujing.netty.protobuf.DateInfo.Employee parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hujing.netty.protobuf.DateInfo.Employee) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object username_ = "";
      /**
       * <code>optional string username = 1;</code>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            username_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>optional int32 age = 2;</code>
       */
      public boolean hasAge() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 age = 2;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional int32 age = 2;</code>
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000002;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 age = 2;</code>
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>optional string address = 3;</code>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            address_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000004);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        address_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.hujing.protobuf.Employee)
    }

    // @@protoc_insertion_point(class_scope:com.hujing.protobuf.Employee)
    private static final com.hujing.netty.protobuf.DateInfo.Employee DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hujing.netty.protobuf.DateInfo.Employee();
    }

    public static com.hujing.netty.protobuf.DateInfo.Employee getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Employee>
        PARSER = new com.google.protobuf.AbstractParser<Employee>() {
      @java.lang.Override
      public Employee parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Employee(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Employee> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Employee> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hujing.netty.protobuf.DateInfo.Employee getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hujing.protobuf.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string username = 1;</code>
     */
    boolean hasUsername();
    /**
     * <code>optional string username = 1;</code>
     */
    java.lang.String getUsername();
    /**
     * <code>optional string username = 1;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>optional int32 age = 2;</code>
     */
    boolean hasAge();
    /**
     * <code>optional int32 age = 2;</code>
     */
    int getAge();

    /**
     * <code>optional string address = 3;</code>
     */
    boolean hasAddress();
    /**
     * <code>optional string address = 3;</code>
     */
    java.lang.String getAddress();
    /**
     * <code>optional string address = 3;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();
  }
  /**
   * Protobuf type {@code com.hujing.protobuf.Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.hujing.protobuf.Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      username_ = "";
      address_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Person();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              username_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              age_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              address_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hujing.netty.protobuf.DateInfo.internal_static_com_hujing_protobuf_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hujing.netty.protobuf.DateInfo.internal_static_com_hujing_protobuf_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hujing.netty.protobuf.DateInfo.Person.class, com.hujing.netty.protobuf.DateInfo.Person.Builder.class);
    }

    private int bitField0_;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object username_;
    /**
     * <code>optional string username = 1;</code>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string username = 1;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string username = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>optional int32 age = 2;</code>
     */
    public boolean hasAge() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 3;
    private volatile java.lang.Object address_;
    /**
     * <code>optional string address = 3;</code>
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string address = 3;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string address = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, username_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, age_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, address_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, username_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, address_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hujing.netty.protobuf.DateInfo.Person)) {
        return super.equals(obj);
      }
      com.hujing.netty.protobuf.DateInfo.Person other = (com.hujing.netty.protobuf.DateInfo.Person) obj;

      if (hasUsername() != other.hasUsername()) return false;
      if (hasUsername()) {
        if (!getUsername()
            .equals(other.getUsername())) return false;
      }
      if (hasAge() != other.hasAge()) return false;
      if (hasAge()) {
        if (getAge()
            != other.getAge()) return false;
      }
      if (hasAddress() != other.hasAddress()) return false;
      if (hasAddress()) {
        if (!getAddress()
            .equals(other.getAddress())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUsername()) {
        hash = (37 * hash) + USERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getUsername().hashCode();
      }
      if (hasAge()) {
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + getAge();
      }
      if (hasAddress()) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddress().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hujing.netty.protobuf.DateInfo.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hujing.netty.protobuf.DateInfo.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hujing.netty.protobuf.DateInfo.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hujing.netty.protobuf.DateInfo.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hujing.netty.protobuf.DateInfo.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hujing.netty.protobuf.DateInfo.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hujing.netty.protobuf.DateInfo.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hujing.netty.protobuf.DateInfo.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hujing.netty.protobuf.DateInfo.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hujing.netty.protobuf.DateInfo.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hujing.netty.protobuf.DateInfo.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hujing.netty.protobuf.DateInfo.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hujing.netty.protobuf.DateInfo.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hujing.protobuf.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hujing.protobuf.Person)
        com.hujing.netty.protobuf.DateInfo.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hujing.netty.protobuf.DateInfo.internal_static_com_hujing_protobuf_Person_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hujing.netty.protobuf.DateInfo.internal_static_com_hujing_protobuf_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hujing.netty.protobuf.DateInfo.Person.class, com.hujing.netty.protobuf.DateInfo.Person.Builder.class);
      }

      // Construct using com.hujing.netty.protobuf.DateInfo.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hujing.netty.protobuf.DateInfo.internal_static_com_hujing_protobuf_Person_descriptor;
      }

      @java.lang.Override
      public com.hujing.netty.protobuf.DateInfo.Person getDefaultInstanceForType() {
        return com.hujing.netty.protobuf.DateInfo.Person.getDefaultInstance();
      }

      @java.lang.Override
      public com.hujing.netty.protobuf.DateInfo.Person build() {
        com.hujing.netty.protobuf.DateInfo.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hujing.netty.protobuf.DateInfo.Person buildPartial() {
        com.hujing.netty.protobuf.DateInfo.Person result = new com.hujing.netty.protobuf.DateInfo.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.age_ = age_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.address_ = address_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hujing.netty.protobuf.DateInfo.Person) {
          return mergeFrom((com.hujing.netty.protobuf.DateInfo.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hujing.netty.protobuf.DateInfo.Person other) {
        if (other == com.hujing.netty.protobuf.DateInfo.Person.getDefaultInstance()) return this;
        if (other.hasUsername()) {
          bitField0_ |= 0x00000001;
          username_ = other.username_;
          onChanged();
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        if (other.hasAddress()) {
          bitField0_ |= 0x00000004;
          address_ = other.address_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hujing.netty.protobuf.DateInfo.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hujing.netty.protobuf.DateInfo.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object username_ = "";
      /**
       * <code>optional string username = 1;</code>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            username_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 1;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>optional int32 age = 2;</code>
       */
      public boolean hasAge() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 age = 2;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional int32 age = 2;</code>
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000002;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 age = 2;</code>
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>optional string address = 3;</code>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            address_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000004);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        address_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.hujing.protobuf.Person)
    }

    // @@protoc_insertion_point(class_scope:com.hujing.protobuf.Person)
    private static final com.hujing.netty.protobuf.DateInfo.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hujing.netty.protobuf.DateInfo.Person();
    }

    public static com.hujing.netty.protobuf.DateInfo.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @java.lang.Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hujing.netty.protobuf.DateInfo.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hujing_protobuf_OneOfAll_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hujing_protobuf_OneOfAll_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hujing_protobuf_Employee_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hujing_protobuf_Employee_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hujing_protobuf_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hujing_protobuf_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nTest.proto\022\023com.hujing.protobuf\"\324\001\n\010On" +
      "eOfAll\0229\n\tdate_type\030\001 \002(\0162&.com.hujing.p" +
      "rotobuf.OneOfAll.DataType\0221\n\010employee\030\002 " +
      "\001(\0132\035.com.hujing.protobuf.EmployeeH\000\022-\n\006" +
      "person\030\003 \001(\0132\033.com.hujing.protobuf.Perso" +
      "nH\000\"\037\n\010DataType\022\007\n\003EMP\020\001\022\n\n\006PERSON\020\002B\n\n\010" +
      "dataBody\":\n\010Employee\022\020\n\010username\030\001 \001(\t\022\013" +
      "\n\003age\030\002 \001(\005\022\017\n\007address\030\003 \001(\t\"8\n\006Person\022\020" +
      "\n\010username\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\017\n\007address" +
      "\030\003 \001(\tB)\n\035com.hujing.netty.sixthexampleB" +
      "\010DateInfo"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_hujing_protobuf_OneOfAll_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hujing_protobuf_OneOfAll_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hujing_protobuf_OneOfAll_descriptor,
        new java.lang.String[] { "DateType", "Employee", "Person", "DataBody", });
    internal_static_com_hujing_protobuf_Employee_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_hujing_protobuf_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hujing_protobuf_Employee_descriptor,
        new java.lang.String[] { "Username", "Age", "Address", });
    internal_static_com_hujing_protobuf_Person_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_hujing_protobuf_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hujing_protobuf_Person_descriptor,
        new java.lang.String[] { "Username", "Age", "Address", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
