// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.hujing.netty.proto;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string RealName = 1;</code>
   */
  String getRealName();
  /**
   * <code>string RealName = 1;</code>
   */
  com.google.protobuf.ByteString
      getRealNameBytes();
}
