// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.hujing.netty.proto;

/**
 * Protobuf type {@code proto.StreamResponseList}
 */
public  final class StreamResponseList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.StreamResponseList)
    StreamResponseListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StreamResponseList.newBuilder() to construct.
  private StreamResponseList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StreamResponseList() {
    streamResponse_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StreamResponseList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StreamResponseList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              streamResponse_ = new java.util.ArrayList<com.hujing.netty.proto.StreamResponse>();
              mutable_bitField0_ |= 0x00000001;
            }
            streamResponse_.add(
                input.readMessage(com.hujing.netty.proto.StreamResponse.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        streamResponse_ = java.util.Collections.unmodifiableList(streamResponse_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hujing.netty.proto.StudentProto.internal_static_proto_StreamResponseList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hujing.netty.proto.StudentProto.internal_static_proto_StreamResponseList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hujing.netty.proto.StreamResponseList.class, com.hujing.netty.proto.StreamResponseList.Builder.class);
  }

  public static final int STREAMRESPONSE_FIELD_NUMBER = 1;
  private java.util.List<com.hujing.netty.proto.StreamResponse> streamResponse_;
  /**
   * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
   */
  public java.util.List<com.hujing.netty.proto.StreamResponse> getStreamResponseList() {
    return streamResponse_;
  }
  /**
   * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
   */
  public java.util.List<? extends com.hujing.netty.proto.StreamResponseOrBuilder> 
      getStreamResponseOrBuilderList() {
    return streamResponse_;
  }
  /**
   * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
   */
  public int getStreamResponseCount() {
    return streamResponse_.size();
  }
  /**
   * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
   */
  public com.hujing.netty.proto.StreamResponse getStreamResponse(int index) {
    return streamResponse_.get(index);
  }
  /**
   * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
   */
  public com.hujing.netty.proto.StreamResponseOrBuilder getStreamResponseOrBuilder(
      int index) {
    return streamResponse_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < streamResponse_.size(); i++) {
      output.writeMessage(1, streamResponse_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < streamResponse_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, streamResponse_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hujing.netty.proto.StreamResponseList)) {
      return super.equals(obj);
    }
    com.hujing.netty.proto.StreamResponseList other = (com.hujing.netty.proto.StreamResponseList) obj;

    if (!getStreamResponseList()
        .equals(other.getStreamResponseList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getStreamResponseCount() > 0) {
      hash = (37 * hash) + STREAMRESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getStreamResponseList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hujing.netty.proto.StreamResponseList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hujing.netty.proto.StreamResponseList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hujing.netty.proto.StreamResponseList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hujing.netty.proto.StreamResponseList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hujing.netty.proto.StreamResponseList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hujing.netty.proto.StreamResponseList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hujing.netty.proto.StreamResponseList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hujing.netty.proto.StreamResponseList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hujing.netty.proto.StreamResponseList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.hujing.netty.proto.StreamResponseList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hujing.netty.proto.StreamResponseList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hujing.netty.proto.StreamResponseList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hujing.netty.proto.StreamResponseList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.StreamResponseList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.StreamResponseList)
      com.hujing.netty.proto.StreamResponseListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hujing.netty.proto.StudentProto.internal_static_proto_StreamResponseList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hujing.netty.proto.StudentProto.internal_static_proto_StreamResponseList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hujing.netty.proto.StreamResponseList.class, com.hujing.netty.proto.StreamResponseList.Builder.class);
    }

    // Construct using com.hujing.netty.proto.StreamResponseList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStreamResponseFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (streamResponseBuilder_ == null) {
        streamResponse_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        streamResponseBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hujing.netty.proto.StudentProto.internal_static_proto_StreamResponseList_descriptor;
    }

    @java.lang.Override
    public com.hujing.netty.proto.StreamResponseList getDefaultInstanceForType() {
      return com.hujing.netty.proto.StreamResponseList.getDefaultInstance();
    }

    @java.lang.Override
    public com.hujing.netty.proto.StreamResponseList build() {
      com.hujing.netty.proto.StreamResponseList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hujing.netty.proto.StreamResponseList buildPartial() {
      com.hujing.netty.proto.StreamResponseList result = new com.hujing.netty.proto.StreamResponseList(this);
      int from_bitField0_ = bitField0_;
      if (streamResponseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          streamResponse_ = java.util.Collections.unmodifiableList(streamResponse_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.streamResponse_ = streamResponse_;
      } else {
        result.streamResponse_ = streamResponseBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hujing.netty.proto.StreamResponseList) {
        return mergeFrom((com.hujing.netty.proto.StreamResponseList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hujing.netty.proto.StreamResponseList other) {
      if (other == com.hujing.netty.proto.StreamResponseList.getDefaultInstance()) return this;
      if (streamResponseBuilder_ == null) {
        if (!other.streamResponse_.isEmpty()) {
          if (streamResponse_.isEmpty()) {
            streamResponse_ = other.streamResponse_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureStreamResponseIsMutable();
            streamResponse_.addAll(other.streamResponse_);
          }
          onChanged();
        }
      } else {
        if (!other.streamResponse_.isEmpty()) {
          if (streamResponseBuilder_.isEmpty()) {
            streamResponseBuilder_.dispose();
            streamResponseBuilder_ = null;
            streamResponse_ = other.streamResponse_;
            bitField0_ = (bitField0_ & ~0x00000001);
            streamResponseBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStreamResponseFieldBuilder() : null;
          } else {
            streamResponseBuilder_.addAllMessages(other.streamResponse_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.hujing.netty.proto.StreamResponseList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.hujing.netty.proto.StreamResponseList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.hujing.netty.proto.StreamResponse> streamResponse_ =
      java.util.Collections.emptyList();
    private void ensureStreamResponseIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        streamResponse_ = new java.util.ArrayList<com.hujing.netty.proto.StreamResponse>(streamResponse_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.hujing.netty.proto.StreamResponse, com.hujing.netty.proto.StreamResponse.Builder, com.hujing.netty.proto.StreamResponseOrBuilder> streamResponseBuilder_;

    /**
     * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
     */
    public java.util.List<com.hujing.netty.proto.StreamResponse> getStreamResponseList() {
      if (streamResponseBuilder_ == null) {
        return java.util.Collections.unmodifiableList(streamResponse_);
      } else {
        return streamResponseBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
     */
    public int getStreamResponseCount() {
      if (streamResponseBuilder_ == null) {
        return streamResponse_.size();
      } else {
        return streamResponseBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
     */
    public com.hujing.netty.proto.StreamResponse getStreamResponse(int index) {
      if (streamResponseBuilder_ == null) {
        return streamResponse_.get(index);
      } else {
        return streamResponseBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
     */
    public Builder setStreamResponse(
        int index, com.hujing.netty.proto.StreamResponse value) {
      if (streamResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStreamResponseIsMutable();
        streamResponse_.set(index, value);
        onChanged();
      } else {
        streamResponseBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
     */
    public Builder setStreamResponse(
        int index, com.hujing.netty.proto.StreamResponse.Builder builderForValue) {
      if (streamResponseBuilder_ == null) {
        ensureStreamResponseIsMutable();
        streamResponse_.set(index, builderForValue.build());
        onChanged();
      } else {
        streamResponseBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
     */
    public Builder addStreamResponse(com.hujing.netty.proto.StreamResponse value) {
      if (streamResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStreamResponseIsMutable();
        streamResponse_.add(value);
        onChanged();
      } else {
        streamResponseBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
     */
    public Builder addStreamResponse(
        int index, com.hujing.netty.proto.StreamResponse value) {
      if (streamResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStreamResponseIsMutable();
        streamResponse_.add(index, value);
        onChanged();
      } else {
        streamResponseBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
     */
    public Builder addStreamResponse(
        com.hujing.netty.proto.StreamResponse.Builder builderForValue) {
      if (streamResponseBuilder_ == null) {
        ensureStreamResponseIsMutable();
        streamResponse_.add(builderForValue.build());
        onChanged();
      } else {
        streamResponseBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
     */
    public Builder addStreamResponse(
        int index, com.hujing.netty.proto.StreamResponse.Builder builderForValue) {
      if (streamResponseBuilder_ == null) {
        ensureStreamResponseIsMutable();
        streamResponse_.add(index, builderForValue.build());
        onChanged();
      } else {
        streamResponseBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
     */
    public Builder addAllStreamResponse(
        java.lang.Iterable<? extends com.hujing.netty.proto.StreamResponse> values) {
      if (streamResponseBuilder_ == null) {
        ensureStreamResponseIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, streamResponse_);
        onChanged();
      } else {
        streamResponseBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
     */
    public Builder clearStreamResponse() {
      if (streamResponseBuilder_ == null) {
        streamResponse_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        streamResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
     */
    public Builder removeStreamResponse(int index) {
      if (streamResponseBuilder_ == null) {
        ensureStreamResponseIsMutable();
        streamResponse_.remove(index);
        onChanged();
      } else {
        streamResponseBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
     */
    public com.hujing.netty.proto.StreamResponse.Builder getStreamResponseBuilder(
        int index) {
      return getStreamResponseFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
     */
    public com.hujing.netty.proto.StreamResponseOrBuilder getStreamResponseOrBuilder(
        int index) {
      if (streamResponseBuilder_ == null) {
        return streamResponse_.get(index);  } else {
        return streamResponseBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
     */
    public java.util.List<? extends com.hujing.netty.proto.StreamResponseOrBuilder> 
         getStreamResponseOrBuilderList() {
      if (streamResponseBuilder_ != null) {
        return streamResponseBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(streamResponse_);
      }
    }
    /**
     * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
     */
    public com.hujing.netty.proto.StreamResponse.Builder addStreamResponseBuilder() {
      return getStreamResponseFieldBuilder().addBuilder(
          com.hujing.netty.proto.StreamResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
     */
    public com.hujing.netty.proto.StreamResponse.Builder addStreamResponseBuilder(
        int index) {
      return getStreamResponseFieldBuilder().addBuilder(
          index, com.hujing.netty.proto.StreamResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
     */
    public java.util.List<com.hujing.netty.proto.StreamResponse.Builder> 
         getStreamResponseBuilderList() {
      return getStreamResponseFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.hujing.netty.proto.StreamResponse, com.hujing.netty.proto.StreamResponse.Builder, com.hujing.netty.proto.StreamResponseOrBuilder> 
        getStreamResponseFieldBuilder() {
      if (streamResponseBuilder_ == null) {
        streamResponseBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.hujing.netty.proto.StreamResponse, com.hujing.netty.proto.StreamResponse.Builder, com.hujing.netty.proto.StreamResponseOrBuilder>(
                streamResponse_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        streamResponse_ = null;
      }
      return streamResponseBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.StreamResponseList)
  }

  // @@protoc_insertion_point(class_scope:proto.StreamResponseList)
  private static final com.hujing.netty.proto.StreamResponseList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hujing.netty.proto.StreamResponseList();
  }

  public static com.hujing.netty.proto.StreamResponseList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamResponseList>
      PARSER = new com.google.protobuf.AbstractParser<StreamResponseList>() {
    @java.lang.Override
    public StreamResponseList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StreamResponseList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StreamResponseList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StreamResponseList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hujing.netty.proto.StreamResponseList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

