// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.hujing.netty.proto;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string city = 1;</code>
   */
  String getCity();
  /**
   * <code>string city = 1;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>int32 code = 2;</code>
   */
  int getCode();
}
