// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.hujing.netty.proto;

public interface StreamResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.StreamResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
   */
  java.util.List<StreamResponse>
      getStreamResponseList();
  /**
   * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
   */
  StreamResponse getStreamResponse(int index);
  /**
   * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
   */
  int getStreamResponseCount();
  /**
   * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
   */
  java.util.List<? extends StreamResponseOrBuilder>
      getStreamResponseOrBuilderList();
  /**
   * <code>repeated .proto.StreamResponse streamResponse = 1;</code>
   */
  StreamResponseOrBuilder getStreamResponseOrBuilder(
          int index);
}
