// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.hujing.netty.proto;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_StreamResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StreamResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_StreamResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_TestStreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_TestStreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_TestStreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_TestStreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStudent.proto\022\005proto\"\035\n\tMyRequest\022\020\n\010u" +
      "sername\030\001 \001(\t\"\036\n\nMyResponse\022\020\n\010RealName\030" +
      "\001 \001(\t\",\n\016StreamResponse\022\014\n\004city\030\001 \001(\t\022\014\n" +
      "\004code\030\002 \001(\005\"C\n\022StreamResponseList\022-\n\016str" +
      "eamResponse\030\001 \003(\0132\025.proto.StreamResponse" +
      "\" \n\021TestStreamRequest\022\013\n\003req\030\001 \001(\t\"\"\n\022Te" +
      "stStreamResponse\022\014\n\004resp\030\001 \001(\t2\305\002\n\016Stude" +
      "ntService\022>\n\025GetRealNameByUsername\022\020.pro" +
      "to.MyRequest\032\021.proto.MyResponse\"\000\022J\n\033Get" +
      "StreamResponseByUsername\022\020.proto.MyReque" +
      "st\032\025.proto.StreamResponse\"\0000\001\022I\n\021SendStr" +
      "eamRequest\022\025.proto.StreamResponse\032\031.prot" +
      "o.StreamResponseList\"\000(\001\022\\\n\037SendStreamRe" +
      "questAndGetResponse\022\030.proto.TestStreamRe" +
      "quest\032\031.proto.TestStreamResponse\"\000(\0010\001B(" +
      "\n\026com.hujing.netty.protoB\014StudentProtoP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_MyRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_proto_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_MyResponse_descriptor,
        new java.lang.String[] { "RealName", });
    internal_static_proto_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_StreamResponse_descriptor,
        new java.lang.String[] { "City", "Code", });
    internal_static_proto_StreamResponseList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_StreamResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_StreamResponseList_descriptor,
        new java.lang.String[] { "StreamResponse", });
    internal_static_proto_TestStreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_TestStreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_TestStreamRequest_descriptor,
        new java.lang.String[] { "Req", });
    internal_static_proto_TestStreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_proto_TestStreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_TestStreamResponse_descriptor,
        new java.lang.String[] { "Resp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
