// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.hujing.netty.proto;

public interface TestStreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.TestStreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string resp = 1;</code>
   */
  String getResp();
  /**
   * <code>string resp = 1;</code>
   */
  com.google.protobuf.ByteString
      getRespBytes();
}
