// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.hujing.netty.proto;

public interface TestStreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.TestStreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string req = 1;</code>
   */
  java.lang.String getReq();
  /**
   * <code>string req = 1;</code>
   */
  com.google.protobuf.ByteString
      getReqBytes();
}
